// ------------------------------------------------------------------------------
//
//  File Name:           VUserMain0.cpp
//  Design Unit Name:    Co-simulation virtual processor test program
//  Revision:            OSVVM MODELS STANDARD VERSION
//
//  Maintainer:          Simon Southwell      email:  simon.southwell@gmail.com
//  Contributor(s):
//     Simon Southwell   simon.southwell@gmail.com
//
//  Description:
//      Co-simulation test transaction source
//
//  Developed by:
//        Simon Southwell
//
//  Revision History:
//    Date      Version    Description
//    09/2022   2022       Initial revision
//
//  This file is part of OSVVM.
//
//  Copyright (c) 2022 by Simon Southwell
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//
// ------------------------------------------------------------------------------

#include <cstdio>
#include <cstdlib>
#include <cstdint>
#include <cmath>
#include <algorithm>
#include <vector>

// Import VProc user API
#include "OsvvmCosim.h"

// I am node 1 context
static int node  = 1;

#ifdef _WIN32
#define srandom srand
#define random rand
#endif

typedef struct {
    uint32_t addr;
    uint32_t wdata;
    uint32_t size;
} wtrans_t;


// ------------------------------------------------------------------------------
// Main entry point for node 1 virtual processor software
//
// VUserMainX has no calling arguments. If runtime configuration required
// then you'll need to read in a configuration file.
//
// ------------------------------------------------------------------------------

extern "C" void VUserMain1()
{
    VPrint("VUserMain1(): node=%d\n", node);

    bool                  error = false;
    uint32_t              wdata = 0;
    OsvvmCosim            cosim(node);

    while (true)
    {
        uint32_t addr  = 0x10000000;
        uint32_t rdata;
        
        // Read four words from 0x10000000 to 0x1000000C, as generated by the
        // interrupt thread, and check they match expected incrementing pattern
        for (int idx = 0; idx < 4; idx++)
        {
            cosim.transRead(addr, &rdata);
            if (rdata != (wdata + idx))
            {
                VPrint("VUserMain1: ***ERROR*** read %08X from address %08X. Expected %08x\n", rdata, addr, (wdata + idx));
                error = true;
                break;
            }
            addr += 4;
        }

        if (!error)
        {
            // Select new start address
            addr = 0xa0002000;
            
            // Write an incrementing pattern to addresses 0xA0002000 to 0xA000200C
            for (int idx = 0; idx < 4; idx++)
            {
                cosim.transWrite(addr, wdata + idx);
                addr  += 4;
            }
            
            // Increment the write data pattern by 16 to get different values at next iteration
            wdata += 0x10;
        }
    }
    
    // Flag to the simulation we're finished, after 10 more iterations
    cosim.tick(10, true, error);


    // If ever got this far then sleep forever
    SLEEPFOREVER;
}

